/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooArg_posPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooArg_posPdf); 

 RooArg_posPdf::RooArg_posPdf(const char *name, const char *title, 
                        RooAbsReal& _DTF_Mass,
                        RooAbsReal& _N,
                        RooAbsReal& _a,
                        RooAbsReal& _b,
                        RooAbsReal& _c) :
   RooAbsPdf(name,title), 
   DTF_Mass("DTF_Mass","DTF_Mass",this,_DTF_Mass),
   N("N","N",this,_N),
   a("a","a",this,_a),
   b("b","b",this,_b),
   c("c","c",this,_c)
 { 
 } 


 RooArg_posPdf::RooArg_posPdf(const RooArg_posPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   DTF_Mass("DTF_Mass",this,other.DTF_Mass),
   N("N",this,other.N),
   a("a",this,other.a),
   b("b",this,other.b),
   c("c",this,other.c)
 { 
 } 



 Double_t RooArg_posPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1./N*pow(DTF_Mass-a,b)*exp(-c*(DTF_Mass-a)) ; 
 } 



