/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOARG_POS_SIDEPDF
#define ROOARG_POS_SIDEPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooArg_pos_sidePdf : public RooAbsPdf {
public:
  RooArg_pos_sidePdf() {} ; 
  RooArg_pos_sidePdf(const char *name, const char *title,
	      RooAbsReal& _dtf_pos_low,
	      RooAbsReal& _N,
	      RooAbsReal& _a,
	      RooAbsReal& _b);
  RooArg_pos_sidePdf(const RooArg_pos_sidePdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooArg_pos_sidePdf(*this,newname); }
  inline virtual ~RooArg_pos_sidePdf() { }

protected:

  RooRealProxy dtf_pos_low ;
  RooRealProxy N ;
  RooRealProxy a ;
  RooRealProxy b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooArg_pos_sidePdf,1) // Your description goes here...
};
 
#endif
