/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooArg_negPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooArg_negPdf); 

 RooArg_negPdf::RooArg_negPdf(const char *name, const char *title, 
                        RooAbsReal& _dtf_neg,
                        RooAbsReal& _N,
                        RooAbsReal& _a,
                        RooAbsReal& _b,
                        RooAbsReal& _c) :
   RooAbsPdf(name,title), 
   dtf_neg("dtf_neg","dtf_neg",this,_dtf_neg),
   N("N","N",this,_N),
   a("a","a",this,_a),
   b("b","b",this,_b),
   c("c","c",this,_c)
 { 
 } 


 RooArg_negPdf::RooArg_negPdf(const RooArg_negPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   dtf_neg("dtf_neg",this,other.dtf_neg),
   N("N",this,other.N),
   a("a",this,other.a),
   b("b",this,other.b),
   c("c",this,other.c)
 { 
 } 



 Double_t RooArg_negPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1./N*pow(dtf_neg-a,b)*exp(-c*(dtf_neg-a)) ; 
 } 



