/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOGENPDFPDF
#define ROOGENPDFPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooGenPdfPdf : public RooAbsPdf {
public:
  RooGenPdfPdf() {} ; 
  RooGenPdfPdf(const char *name, const char *title,
	      RooAbsReal& _dtf_neg_low,
	      RooAbsReal& _N,
	      RooAbsReal& _a,
	      RooAbsReal& _b,
	      RooAbsReal& _c);
  RooGenPdfPdf(const RooGenPdfPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooGenPdfPdf(*this,newname); }
  inline virtual ~RooGenPdfPdf() { }

protected:

  RooRealProxy dtf_neg_low ;
  RooRealProxy N ;
  RooRealProxy a ;
  RooRealProxy b ;
  RooRealProxy c ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooGenPdfPdf,1) // Your description goes here...
};
 
#endif
