/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooGenPdfPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooGenPdfPdf); 

 RooGenPdfPdf::RooGenPdfPdf(const char *name, const char *title, 
                        RooAbsReal& _dtf_neg_low,
                        RooAbsReal& _N,
                        RooAbsReal& _a,
                        RooAbsReal& _b,
                        RooAbsReal& _c) :
   RooAbsPdf(name,title), 
   dtf_neg_low("dtf_neg_low","dtf_neg_low",this,_dtf_neg_low),
   N("N","N",this,_N),
   a("a","a",this,_a),
   b("b","b",this,_b),
   c("c","c",this,_c)
 { 
 } 


 RooGenPdfPdf::RooGenPdfPdf(const RooGenPdfPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   dtf_neg_low("dtf_neg_low",this,other.dtf_neg_low),
   N("N",this,other.N),
   a("a",this,other.a),
   b("b",this,other.b),
   c("c",this,other.c)
 { 
 } 



 Double_t RooGenPdfPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1/N*pow(dtf_neg_low-a,b)*exp(-c*(dtf_neg_low-a)) ; 
 } 



