/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdf); 

 RooMyPdf::RooMyPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _N,
                        RooAbsReal& _a,
                        RooAbsReal& _b,
                        RooAbsReal& _c) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   N("N","N",this,_N),
   a("a","a",this,_a),
   b("b","b",this,_b),
   c("c","c",this,_c)
 { 
 } 


 RooMyPdf::RooMyPdf(const RooMyPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   N("N",this,other.N),
   a("a",this,other.a),
   b("b",this,other.b),
   c("c",this,other.c)
 { 
 } 



 Double_t RooMyPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1/N*pow((x-a),b)*exp(-c*(x-a)) ; 
 } 



